apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-29T06:31:20Z"
  labels:
    app: nginx-deployment
  name: nginx-deployment
  namespace: namespace2
  resourceVersion: "1249"
  uid: f135161b-3bf0-4820-8188-7bcd3925ba54
spec:
  clusterIP: 10.97.196.131
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    nodePort: 32386
    port: 80
    protocol: TCP
    targetPort: 80
  - name: http-alt
    nodePort: 32387
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-deployment
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
